submit jawaban Soal 1, Soal 2, Soal 3
irzaardian/latihan pull request #3
Opened 2022-07-14 07:31 UTC by irzaardian

2022-07-14 14:53 UTC, dinidininta requested changes

2022-07-14 14:53 UTC, dinidininta commented on 14-07-2022/Soal1.java
> +        if (uang == Cola) {
dan cak ini sudah oke. 👍 
ado cara lain yg biso dicubo, yaitu pake looping. konsepny adalah looping nominal uang yg dimasukke sampe dak biso beli minuman yg tersedia lagi.

2022-07-14 14:53 UTC, dinidininta commented on 14-07-2022/Soal1.java
> +            System.out.println("Uang tidak mencukupi");
nah kalo pake looping, pengecekan uang tidak mencukupi ini biso dipindah ke step pertamo. biar program langsung berhenti (dak masuk looping) begitu tau uangny dak cukup

2022-07-14 14:53 UTC, dinidininta commented on 14-07-2022/Soal2.java
> +            System.out.print("Bilangan primanya adalah ");
dan, penjelasan itu maksudny dak perlu di print 😅
cukup jumlah bilangan primanyo be ado berapo

2022-07-14 14:53 UTC, dinidininta commented on 14-07-2022/Soal2.java
> +            System.out.print("Bilangan primanya adalah ");
jadi dak perlu dicek ado berapo `jumlah_bilangan_prima` nyo. langsung di print bae

2022-07-14 14:53 UTC, dinidininta commented on 14-07-2022/Soal3.java
> +        System.out.println(id_terpanjang);
mantap djiwa 👍

2022-07-14 16:20 UTC, dinidininta approved these changes

2022-07-14 16:22 UTC, merged

2022-07-24 15:15 UTC, Jhstvf4t commented
I don't have money anymore to go out to the workshop, I want to eat, let alone me☹️